version: '3.7'

services:
  app:
    build:
      context: .
    container_name: django_dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
    depends_on:
      - db
  db: 
    image: postgres:12.0-alpine
    container_name: postgres_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=breath
  
volumes: 
  postgres_data:
