version: '3.7'

services: 
  app:
    build:
      context: .
    container_name: django
    volumes:
      - static_data:/vol/web
    depends_on: 
      - db
    env_file: 
      - ./app/.env

  proxy:
    build:
      context: ./proxy
    container_name: nginx
    volumes:
      - static_data:/vol/static
    ports:
      - "80:80"
    depends_on: 
      - app

  db:
    image: postgres:12.0-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=breath

volumes: 
  static_data:
  postgres_data:


  
